### ISSUE TITLE
TemplateDoesNotExist

### ISSUE THREAD

**Issue by IvanMadera** [Codingplace42/django-simple-chatbot#3]
Traceback (most recent call last):
  File "/home/ivan/Documentos/django-project/simple_chatbot/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ivan/Documentos/django-project/simple_chatbot/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/ivan/Documentos/django-project/simple_chatbot/venv/lib/python3.8/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/ivan/Documentos/django-project/simple_chatbot/venv/lib/python3.8/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/home/ivan/Documentos/django-project/simple_chatbot/venv/lib/python3.8/site-packages/rest_framework/renderers.py", line 723, in render
    template = loader.get_template(self.template)
  File "/home/ivan/Documentos/django-project/simple_chatbot/venv/lib/python3.8/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: rest_framework/api.html

**Comment by I1ght** [comment]
Getting the same issue, Tag me too if you find a solution.
